AWSTemplateFormatVersion: "2010-09-09"

Description:
  Kazunori_Kurata_raisetech_CloudFormation

Resources:
  Kurata-vpc-02:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: Kurata_vpc_02


  Kurata-igw-02:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Kurata_igw_02


  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Kurata-vpc-02
      InternetGatewayId: !Ref Kurata-igw-02


  Kurata_subnet_pub1a-02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref Kurata_vpc_02
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Kurata_subnet_pub1a-02


  Kurata_subnet_pub1c-02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref Kurata_vpc_02
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Kurata_subnet_pub1c-02


  Kurata_subnet_pri1a-02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref Kurata_vpc_02
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Kurata_subnet_pri1a-02


  Kurata_subnet_pri1c-02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref Kurata_vpc_02
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Kurata_subnet_pri1c-02


  Kurata_rt_pub-02:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Kurata_vpc_02
      Tags:
        - Key: Name
          Value: Kurata_rt_pub-02


  Kurata_pub_Route1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref Kurata_rt_pub-02
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Kurata-igw-02


  routeTableAssocPublic01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Kurata_subnet_pub1a-02
      RouteTableId: !Ref Kurata_rt_pub-02


  routeTableAssocPublic02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Kurata_subnet_pub1c-02
      RouteTableId: !Ref Kurata_rt_pub-02


  Kurata_rt_pri-02:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Kurata_vpc_02
      Tags:
        - Key: Name
          Value: Kurata_rt_pri-02


  routeTableAssocPrivate01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Kurata_subnet_pri1a-02
      RouteTableId: !Ref Kurata_rt_pri-02


  routeTableAssocPrivate02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Kurata_subnet_pri1c-02
      RouteTableId: !Ref Kurata_rt_pri-02

Outputs:
  StackVPC:
    Description: VPC's ID
    Value: !Ref Kurata-vpc-02
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"

  StackPublicSubnet1A:
    Description: Public Subnet's ID
    Value: !Ref Kurata_subnet_pub1a-02
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1A"

  StackPrivateSubnet1A:
    Description: Private Subnet's ID
    Value: !Ref Kurata_subnet_pri1a-02
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1A"

  StackPublicSubnet1C:
    Description: Public Subnet's ID
    Value: !Ref Kurata_subnet_pub1c-02
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1C"

  StackPrivateSubnet1C:
    Description: Private Subnet's ID
    Value: !Ref Kurata_subnet_pri1c-02
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1C"
